#!/usr/bin/env bash
gnome-terminal --title="Logstash" -x sh -c 'docker run --rm --network tap -it --ip 10.0.100.8 -v "$(dirname "$(readlink -f "$0")")/config/:/usr/share/logstash/pipeline/" --name Logstash docker.elastic.co/logstash/logstash:7.7.0'
