#!/usr/bin/env bash
# Build image
docker build ../../ --tag project:kafka

# Stop
docker stop ZooKeeper

# Remove previuos container 
docker container rm ZooKeeper

docker run -e KAFKA_ACTION=start-zk --network tap --ip 10.0.100.22 -p 2181:2181 --name ZooKeeper -it project:kafka
